### ISSUE TITLE
Progress

### ISSUE THREAD

**Issue by kababoom** [JSdeJong/SmartMAir#1]
Thanks for creating this, it's useful....
Before I start digging did you get any further then this?

My goal is simple, I would like to control the unit(s) mostly to watch for too high or too low settings (teenage kids). So readout values, if exceeding threshold set value ...

**Comment by JSdeJong** [comment]
I did have a list of status codes with different setting which shows the different offsets changing. Unfortunately not saved and laptop rebooted.

The APK does some sort of mapping but I'm totally crap at reading Java code. So I cannot reverse engineer the mapping.

Unfortunately I haven't had much time to dig through it just yet.

**Comment by kababoom** [comment]
I'm used to c# so can read java a bit as well but not sure if we need it. Was there any secret keys involved or is all just plain api calls? if so we can just create these instead.
Not sure about your goal in this, some home automation?
We can also discuss this offline because I guess (from your name) you're NL based too.

**Comment by savage008** [comment]
@kababoom ping
